perpustakaan/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('/');
Route::get('/about', 'AboutController@about')->name('about');
Route::get('/katalog', 'KatalogController@koleksi')->name('katalog');
Route::get('/lokasi', 'KatalogController@lokasi')->name('lokasi');
Route::get('/informasi', 'KatalogController@informasi')->name('informasi');


// register dan login//
Route::get('/register', 'PostController@register')->name('register');
Route::post('/data/register', 'PostController@store');
Route::get('/login', 'PostController@login')->name('login');
Route::post('/simpan', 'PostController@simpan')->name('simpan');
Route::get('/logout', 'PostController@logout')->name('logout');
Route::get('/dashboard', 'PostController@index')->name('dashboard');

Route::group(['middleware' => ['auth']], function () {
        //
        
    // Manage Akun//
    Route::name('manage-akun.')->prefix('manage-akun')->group(function() {
        Route::get('', 'AnggotaController@index')->name('index');
        Route::get('create', 'AnggotaController@create')->name('create');
        Route::post('store', 'AnggotaController@store')->name('store');
        Route::get('show/{users_id}', 'AnggotaController@show')->name('show');
        Route::get('edit/{users_id}', 'AnggotaController@edit')->name('edit');
        Route::put('update/{id}', 'AnggotaController@update')->name('update');
        Route::get('status/{id}','AnggotaController@status')->name('status');
    });

    // Role Anggota//
    Route::name('roles.')->prefix('roles')->group(function() {
        Route::get('', 'RolesController@index')->name('index');
        Route::get('add', 'RolesController@add')->name('add');
        Route::post('store', 'RolesController@store')->name('store');
        Route::get('edit/{id}', 'RolesController@edit')->name('edit');
        Route::put('update/{id}', 'RolesController@update')->name('update');
        Route::delete('destroy/{id}', 'RolesController@destroy')->name('destroy');
    });


    // Manage Buku //
    Route::name('master-buku.')->prefix('master-buku')->group(function() {
        Route::get('', 'BukuController@index')->name('index');
        Route::get('blank', 'BukuController@blank')->name('blank');
        Route::get('nonaktif', 'BukuController@nonaktif')->name('nonaktif');
        Route::get('create', 'BukuController@create')->name('create');
        Route::post('load', 'BukuController@load')->name('load');
        Route::get('show/{buku_id}', 'BukuController@show')->name('show');
        Route::get('edit/{buku_id}', 'BukuController@edit')->name('edit');
        Route::put('update/{buku_id}', 'BukuController@update')->name('update');
        Route::delete('destroy/{buku_id}', 'BukuController@destroy')->name('destroy');
        Route::get('status/{id}','BukuController@status')->name('status');
        Route::get('ambil/{id}','BukuController@ambil')->name('ambil');
    });

    // Peminjaman Buku //
    Route::name('pinjam-buku.')->prefix('pinjam-buku')->group(function() {
        Route::get('', 'PeminjamanController@index')->name('index');
        Route::get('cek/{id}', 'PeminjamanController@cek')->name('cek');
        Route::get('form', 'PeminjamanController@form')->name('form');
        Route::post('save', 'PeminjamanController@save')->name('save');
        Route::get('setujui/{id}', 'PeminjamanController@setujui')->name('setujui');
        Route::get('tolak/{id}', 'PeminjamanController@tolak')->name('tolak');
    });

    // Pengembalian Buku //
    Route::name('pengembalian-buku.')->prefix('pengembalian-buku')->group(function() {
        Route::get('', 'PengembalianController@index')->name('index');
        Route::get('/{id}', 'PengembalianController@kembalikan')->name('kembalikan');
        Route::get('edit/{pinjam_id}', 'PengembalianController@edit')->name('edit');
        Route::put('update', 'PengembalianController@update')->name('update');
    });

    // Laporan Peminjaman Buku //
    Route::name('laporan.')->prefix('laporan')->group(function() {
        Route::get('', 'LaporanController@index')->name('index');
    });

});

perpustakaan/app/Models/Buku.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    protected $table = 'buku';
    
}

perpustakaan/app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BukuController extends Controller
{
    //
    public function index()
    {
        $databuku = DB::table('buku')->get();
        return view('buku.index', compact('databuku'));
    }

    public function blank()
    {
        $databuku = DB::table('buku')->where('stok_buku', '<', 1)->get();
        return view('buku.index', compact('databuku'));
    }
   
    public function nonaktif()
    {
        $databuku = DB::table('buku')->where('status_buku', '!=', 1)->get();
        return view('buku.index', compact('databuku'));
    }

    public function create()
    {
        return view('buku.create');
    }

    public function load(Request $request)
    {
        $request->validate(
            [
            'judul' => 'required',
            'deskripsi' => 'required',
            'pengarang' => 'required',
            'tahun' => 'required',
            'kode_buku' => 'required', 
            'stok_buku' => 'required', 
            'lokasi' => 'required',
            'status_buku' => '',
            ],
            [
                'judul.required' => 'judul harus diisi',
                'deskripsi.required'  => 'deskripsi harus diisi',
                'pengarang.required'  => 'pengarang harus diisi',
                'tahun.required'  => 'tahun harus diisi',
                'kode_buku.required'  => 'kode_buku harus diisi', 
                'stok_buku.required'  => 'stok_buku harus diisi',
                'lokasi.required'  => 'lokasi harus diisi', 
            ],
        );

        DB::table('buku')->insert(
            [
                'judul' => $request['judul'], 
                'deskripsi' => $request['deskripsi'],
                'pengarang' => $request['pengarang'],
                'tahun' => $request['tahun'],
                'kode_buku' => $request['kode_buku'],
                'stok_buku' => $request['stok_buku'],
                'lokasi' => $request['lokasi'],
                'status_buku' => $request['status_buku'],
            ],
        );
        return redirect()->route('master-buku.index')->with('success', 'Data Berhasil Disimpan');
    }

    public function show($id)
    {
        $databuku = DB::table('buku')->where('id', $id)->first();

        return view('buku.show', compact('databuku'));
    }

    public function edit($id)
    {
        $databuku = DB::table('buku')->where('id', $id)->first();

        return view('buku.edit', compact('databuku'));
    }

    public function update(Request $request, $id)
    {
        $request->validate(
            [
             'judul' => 'required',
             'deskripsi' => 'required',
             'pengarang' => 'required',
             'tahun' => 'required',
             'kode_buku' => 'required', 
             'stok_buku' => 'required',
             'lokasi' => 'required',
             'status_buku' => '',
            ],
            [
                'judul.required' => 'judul harus diisi',
                'deskripsi.required'  => 'deskripsi harus diisi',
                'pengarang.required'  => 'pengarang harus diisi',
                'tahun.required'  => 'tahun harus diisi',
                'kode_buku.required'  => 'kode_buku harus diisi', 
                'stok_buku.required'  => 'stok_buku harus diisi',
                'lokasi.required'  => 'lokasi harus diisi', 
            ]
        );

        DB::table('buku')
              ->where('id', $id)
              ->update(
                  [
                    'judul' => $request['judul'], 
                    'deskripsi' => $request['deskripsi'],
                    'pengarang' => $request['pengarang'],
                    'tahun' => $request['tahun'],
                    'kode_buku' => $request['kode_buku'],
                    'stok_buku' => $request['stok_buku'],
                    'lokasi' => $request['lokasi'],
                    'status_buku' => $request['status_buku'],
                  ]
                );
                
        return redirect()->route('master-buku.index')->with('success', 'Data Berhasil Disimpan');
    }

    public function destroy($id)
    {
        DB::table('buku')->where('id', '=', $id)->delete();

        return redirect()->route('master-buku.index')->with('success', 'Data Buku Berhasil Dihapus');
    }

    public function status($id)
    {
        $databuku = DB::table('buku')->where('id', $id)->first(); 
        $cekdata = $databuku->status_buku;
        if ($cekdata == 1){
            DB::table('buku')->where('id', $id)->update([
                'status_buku'=>0
            ]);
        } else {
            DB::table('buku')->where('id', $id)->update([
                'status_buku'=>1
            ]);
        }
        return redirect()->route('master-buku.index')->with('success', 'Status Buku Berhasil diubah');
    }

    public function ambil($id)
    {
        $buku = DB::table('buku')->where('id', $id)->first();
        $stok_now = $buku->stok_buku;
        $stok_new = $stok_now - 1;
        
        DB::table('buku')->where('id', $id)->update([
            'stok_buku'=>$stok_new,
        ]);
        return redirect()->route('master-buku.index')->with('success', 'Stok Buku Berhasil diubah');
    }
}

perpustakaan/resources/views/buku/create.blade.php
@extends('layout.dasbor')
 
@section('judul')

Tambah Buku
@endsection

@section('konten')
<p>
    <a href="javascript:history.back()" class="btn btn-sm btn-flat btn-warning">Back</a>
</p>
  <form action="{{ route('master-buku.load') }}" method="post">
    @csrf
    <div class="form-group">
      <label >Judul Buku</label>
      <input type="text" name="judul" class="form-control">
    </div>
    @error('judul')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div class="form-group">
      <label for="exampleInputDeskripsi">Deskripsi</label>
      <textarea name="deskripsi" cols="30" rows="10" class="form-control"></textarea>
    </div>
    <div class="form-group">
      <label >Pengarang</label>
      <input type="text" name="pengarang" class="form-control">
    </div>
    @error('pengarang')
       <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div class="form-group">
      <label >Tahun</label>
      <input type="text" name="tahun" class="form-control">
    </div>
    @error('tahun')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div class="form-group">
      <label >Kode Buku</label>
      <input type="number" name="kode_buku" class="form-control">
    </div>
    @error('kode_buku')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div class="form-group">
      <label >Stok Buku</label>
      <input type="number" name="stok_buku" class="form-control">
    </div>
    @error('stok_buku')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div class="form-group">
      <label >Lokasi Buku</label>
      <input type="text" name="lokasi" class="form-control">
    </div>
    @error('lokasi')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror    <div class="form-group">
    <div class="form-group">
      <label >Status</label>
      <input type="number" name="status" class="form-control">
    </div>
    @error('status')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <button type="submit" class="btn btn-primary">Submit</button>
    @error('deskripsi')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
  </form>

@endsection
 
 

perpustakaan/resources/views/buku/edit.blade.php
@extends('layout.dasbor')
@section('judul')
Edit Data Buku {{$databuku->judul}}
@endsection

@section('konten')
  <form action="{{ route('master-buku.update',$databuku->id) }}" method="POST">
      @csrf
      @method('put')
      <div class="form-group">
        <label >Judul</label>
        <input type="text" value="{{$databuku->judul}}" name="judul" class="form-control">
      </div>
      @error('judul')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <div class="form-group">
        <label >Deskripsi</label>
        <textarea value="{{$databuku->deskripsi}}" name="deskripsi" cols="30" rows="10" class="form-control"></textarea>
      </div>
      @error('email')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <div class="form-group">
        <label >Pengarang</label>
        <input type="text" value="{{$databuku->pengarang}}" name="pengarang" class="form-control">
      </div>
      <div class="form-group">
        <label >Tahun</label>
        <input type="number" value="{{$databuku->tahun}}" name="tahun" class="form-control">
      </div>
      @error('tahun')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <div class="form-group">
        <label >Kode Buku</label>
        <input type="number" value="{{$databuku->kode_buku}}" name="kode_buku" class="form-control">
      </div>
      @error('kode_buku')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <div class="form-group">
        <label >Stok Buku</label>
        <input type="number" value="{{$databuku->stok_buku}}" name="stok_buku" class="form-control">
      </div>
      @error('stok_buku')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <div class="form-group">
        <label >Lokasi Buku</label>
        <input type="teks" value="{{$databuku->lokasi}}" name="lokasi" class="form-control">
      </div>
      @error('lokasi')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <div class="form-group">
        <label >Status</label>
        <input type="number" value="{{$databuku->status_buku}}" name="status_buku" class="form-control">
      </div>
      @error('status')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <button type="submit" class="btn btn-primary">Update</button>
      @error('pengarang')
       <div class="alert alert-danger">{{ $message }}</div>
      @enderror
  </form>

@endsection

perpustakaan/resources/views/buku/index.blade.php
@extends('layout.dasbor')
 
@section('judul')
Data Buku
@endsection

@section('konten')
@if(Auth::user()->roles_id == 1)
<a href="{{ route('master-buku.create') }}" class="btn btn-primary btn-sm mb-3"><i class="fas fa-plus"></i>         Tambah Buku</a>
@endif
<button type="submit" value="Refresh" class="btn btn-light btn-sm mb-3"><i class="fas fa-sync" onClick="document.location.reload(true)">             Refresh</i></button>
<a href="{{ route('master-buku.index') }}" class="btn btn-success btn-sm mb-3"> All Buku</a>
<a href="{{ route('master-buku.blank') }}" class="btn btn-danger btn-sm mb-3"> Stok Buku Habis</a>
<a href="{{ route('master-buku.nonaktif') }}" class="btn btn-info btn-sm mb-3"> Buku Nonaktif</a>
@if (session('success'))
    <div class="alert alert-success">
      {{ session('success') }}
    </div>
@endif

<div class="card-body table-responsive p-0" style="height: 300px;">
  <table class="table">
    <thead class="table-dark">
      <tr>
        <th scope="col">#</th>
        @if(Auth::user()->roles_id == 1)
        <th scope="col">Keadaan</th>
        <th scope="col">Tindak</th>
        @endif
        <th scope="col">Pinjam</th>
        <th scope="col">Judul</th>
        <th scope="col">Deskripsi</th>
        <th scope="col">Pengarang</th>
        <th scope="col">Tahun</th>
        <th scope="col">Kode_Buku</th>
        <th scope="col">Stok_Buku</th>
        <th scope="col">Lokasi</th>
        <th scope="col">Status</th>
        @if(Auth::user()->roles_id == 1)
        <th scope="col">Action</th>
        @endif
      </tr>
    </thead>
    <tbody>
        @forelse ($databuku as $key => $item)
            <tr>
                <td>{{$key + 1}}</td>

                @if(Auth::user()->roles_id == 1)
                <td>
                  @if($item->status_buku == 1)
                  <a href="{{ route('master-buku.status',$item->id) }}" class="btn btn-danger btn-sm">Non-Aktifkan</a>
                  @else
                  <a href="{{ route('master-buku.status',$item->id) }}" class="btn btn-success btn-sm">Aktifkan</a>
                  @endif
                </td>
                <td>
                  <a href="{{ route('master-buku.ambil',$item->id) }}" class="btn btn-primary btn-sm">Kurangi Stok</a>
                </td>
                @endif

                <td>
                  <a href="{{ route('pinjam-buku.cek',$item->id) }}" class="btn btn-warning btn-sm">Pinjam Buku</a>
                </td>
                <td>{{$item->judul}}</td>
                <td>{{$item->deskripsi}}</td>
                <td>{{$item->pengarang}}</td>
                <td>{{$item->tahun}}</td>
                <td>{{$item->kode_buku}}</td>
                <td>{{$item->stok_buku}}</td>
                <td>{{$item->lokasi}}</td>
                <td><span class="badge {{ ($item->status_buku == 1) ? 'bg-success' : 'bg-danger' }}">{{ ($item->status_buku == 1) ? 'Aktif' : 'Tidak Aktif' }}</span></td>
                @if(Auth::user()->roles_id == 1)
                <td>
                  
                    <form action="{{ route('master-buku.destroy',$item->id) }}" method="POST">
                          @csrf
                          @method('delete')
                          <a href="{{ route('master-buku.show',$item->id) }}" class="btn btn-info btn-sm"><i class="fas fa-eye"></i></a>
                          <a href="{{ route('master-buku.edit',$item->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-pen"></i></a>
                          <button type="submit" value="delete" class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>

                    </form>
                </td>
                @endif
            </tr>
        @empty
          <tr>
              <td>Data Masih Kosong</td>
          </tr>
        @endforelse
    </tbody>
  </table>
</div>
@endsection

perpustakaan/resources/views/buku/show.blade.php
@extends('layout.dasbor')
 
 @section('konten')
 <h1>{{$databuku->judul}}</h1>
 <p>{{$databuku->deskripsi}}</p>
 <p>{{$databuku->pengarang}}</p>
 <p>{{$databuku->tahun}}</p>
 <p>{{$databuku->kode_buku}}</p>
 <p>{{$databuku->stok_buku}}</p>
 <p>{{$databuku->lokasi}}</p>
 <p>{{$databuku->status_buku}}</p>

 <a href="{{ route('master-buku.index') }}" class="btn btn-secondary">Back</a>

 @endsection