perpustakaan/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('/');
Route::get('/about', 'AboutController@about')->name('about');
Route::get('/katalog', 'KatalogController@koleksi')->name('katalog');
Route::get('/lokasi', 'KatalogController@lokasi')->name('lokasi');
Route::get('/informasi', 'KatalogController@informasi')->name('informasi');


// register dan login//
Route::get('/register', 'PostController@register')->name('register');
Route::post('/data/register', 'PostController@store');
Route::get('/login', 'PostController@login')->name('login');
Route::post('/simpan', 'PostController@simpan')->name('simpan');
Route::get('/logout', 'PostController@logout')->name('logout');
Route::get('/dashboard', 'PostController@index')->name('dashboard');

Route::group(['middleware' => ['auth']], function () {
        //
        
    // Manage Akun//
    Route::name('manage-akun.')->prefix('manage-akun')->group(function() {
        Route::get('', 'AnggotaController@index')->name('index');
        Route::get('create', 'AnggotaController@create')->name('create');
        Route::post('store', 'AnggotaController@store')->name('store');
        Route::get('show/{users_id}', 'AnggotaController@show')->name('show');
        Route::get('edit/{users_id}', 'AnggotaController@edit')->name('edit');
        Route::put('update/{id}', 'AnggotaController@update')->name('update');
        Route::get('status/{id}','AnggotaController@status')->name('status');
    });

    // Role Anggota//
    Route::name('roles.')->prefix('roles')->group(function() {
        Route::get('', 'RolesController@index')->name('index');
        Route::get('add', 'RolesController@add')->name('add');
        Route::post('store', 'RolesController@store')->name('store');
        Route::get('edit/{id}', 'RolesController@edit')->name('edit');
        Route::put('update/{id}', 'RolesController@update')->name('update');
        Route::delete('destroy/{id}', 'RolesController@destroy')->name('destroy');
    });


    // Manage Buku //
    Route::name('master-buku.')->prefix('master-buku')->group(function() {
        Route::get('', 'BukuController@index')->name('index');
        Route::get('blank', 'BukuController@blank')->name('blank');
        Route::get('nonaktif', 'BukuController@nonaktif')->name('nonaktif');
        Route::get('create', 'BukuController@create')->name('create');
        Route::post('load', 'BukuController@load')->name('load');
        Route::get('show/{buku_id}', 'BukuController@show')->name('show');
        Route::get('edit/{buku_id}', 'BukuController@edit')->name('edit');
        Route::put('update/{buku_id}', 'BukuController@update')->name('update');
        Route::delete('destroy/{buku_id}', 'BukuController@destroy')->name('destroy');
        Route::get('status/{id}','BukuController@status')->name('status');
        Route::get('ambil/{id}','BukuController@ambil')->name('ambil');
    });

    // Peminjaman Buku //
    Route::name('pinjam-buku.')->prefix('pinjam-buku')->group(function() {
        Route::get('', 'PeminjamanController@index')->name('index');
        Route::get('cek/{id}', 'PeminjamanController@cek')->name('cek');
        Route::get('form', 'PeminjamanController@form')->name('form');
        Route::post('save', 'PeminjamanController@save')->name('save');
        Route::get('setujui/{id}', 'PeminjamanController@setujui')->name('setujui');
        Route::get('tolak/{id}', 'PeminjamanController@tolak')->name('tolak');
    });

    // Pengembalian Buku //
    Route::name('pengembalian-buku.')->prefix('pengembalian-buku')->group(function() {
        Route::get('', 'PengembalianController@index')->name('index');
        Route::get('/{id}', 'PengembalianController@kembalikan')->name('kembalikan');
        Route::get('edit/{pinjam_id}', 'PengembalianController@edit')->name('edit');
        Route::put('update', 'PengembalianController@update')->name('update');
    });

    // Laporan Peminjaman Buku //
    Route::name('laporan.')->prefix('laporan')->group(function() {
        Route::get('', 'LaporanController@index')->name('index');
    });

});

perpustakaan/app/Models/Roles.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Roles extends Model
{
    public $timestamps = false;
    protected $table = 'roles';

}

perpustakaan/app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class RolesController extends Controller
{
    public function index()
    {
        
        $rolesdata = DB::table('roles')->get();
        return view('roles.index',compact('rolesdata'));
    }

    public function add()
    {
        return view('roles.add');
    }

    public function store(Request $request)
    {
        $request->validate(
            [
            'peran' => 'required',
            ],
            [
                'peran.required' => 'peran harus diisi',
            ],
            
        );

        DB::table('roles')->insert(
            [
                'peran' => $request['peran'], 
            ]
        );
  
        return redirect('/roles')->with('best', 'Data  Roles berhasil ditambahkan!');;
    }

    public function edit($id)
    {
        $rolesdata = DB::table('roles')->where('id', $id)->first();

        return view('roles.edit', compact('rolesdata'));
    }

    public function update(Request $request, $id)
    {
        $request->validate(
            [
            'peran' => 'required',
            ],
            [
                'peran.required' => 'peran harus diisi',
            ]
        );

        DB::table('roles')
              ->where('id', $id)
              ->update(
                  [
                    'peran' => $request['peran'], 
                  ]
                );

        return redirect('/roles')->with('best', 'Data Berhasil Disimpan');
    }

    public function destroy($id)
    {
        DB::table('roles')->where('id', '=', $id)->delete();

        return redirect('/roles')->with('best', 'Data Roles Berhasil Dihapus');
    }
}

perpustakaan/resources/views/roles/add.blade.php
@extends('layout.dasbor')
 
@section('judul')

Tambah Roles
@endsection

@section('konten')
<p>
    <a href="javascript:history.back()" class="btn btn-sm btn-flat btn-warning">Back</a>
</p>
  <form action="{{ route('roles.store') }}" method="POST">
    @csrf
    <div class="form-group">
      <label >Nama Roles</label>
      <input type="text" name="peran" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    @error('peran')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
  </form>


@endsection
 
 

perpustakaan/resources/views/roles/edit.blade.php
@extends('layout.dasbor')
@section('judul')
Edit Roles {{$rolesdata->roles}}
@endsection

@section('konten')
  <form action="{{ route('roles.update',$rolesdata->id) }}" method="POST">
      @csrf
      @method('put')
      <div class="form-group">
        <label >Nama Anggota</label>
        <input type="text" value="{{$rolesdata->roles}}" name="peran" class="form-control">
      </div>
      <button type="submit" class="btn btn-primary">Update</button>
      @error('peran')
       <div class="alert alert-danger">{{ $message }}</div>
      @enderror
  </form>
@endsection

perpustakaan/resources/views/roles/index.blade.php
@extends('layout.dasbor')
 
@section('konten')

<a href="{{ route('roles.add') }}" class="btn btn-primary btn-sm mb-3"><i class="fas fa-plus"></i>         Tambah Roles</a>
<button type="submit" value="Refresh" class="btn btn-secondary btn-sm mb-3"><i class="fas fa-sync" onClick="document.location.reload(true)">             Refresh</i></button>
@if (session('best'))
    <div class="alert alert-success">
      {{ session('best') }}
    </div>
@endif

<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col md-8 col-md-offset-2">#</th>
      <th scope="col md-8 col-md-offset-2">Roles</th>
      <th scope="col">Created_at</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
      @forelse ($rolesdata as $key => $item)
          <tr>
              <td>{{$key + 1}}</td>
              <td>{{$item->peran}}</td>
              <td>{{$item->created_at}}</td>
              <td>

                  <form action="{{ route('roles.destroy',$item->id) }}" method="POST">
                        @csrf
                        @method('delete')
                        <a href="{{ route('roles.edit',$item->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-pen"></i></a>
                        <button type="submit" value="delete" class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
                  </form>
              </td>
          </tr>
      @empty
         <tr>
             <td>Data Masih Kosong</td>
         </tr>
      @endforelse
  </tbody>
</table>
@endsection

@section('scripts')
  <script type="text/javascript">
      $(document).ready(function(){
          // btn refresh 
            $('.btn-refresh').click(function(e){
                e.preventDefault();
                $('.preloader').fadeIn();
                location.reload();
            })
       })
  </script>
@endsection 