perpustakaan/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('/');
Route::get('/about', 'AboutController@about')->name('about');
Route::get('/katalog', 'KatalogController@koleksi')->name('katalog');
Route::get('/lokasi', 'KatalogController@lokasi')->name('lokasi');
Route::get('/informasi', 'KatalogController@informasi')->name('informasi');


// register dan login//
Route::get('/register', 'PostController@register')->name('register');
Route::post('/data/register', 'PostController@store');
Route::get('/login', 'PostController@login')->name('login');
Route::post('/simpan', 'PostController@simpan')->name('simpan');
Route::get('/logout', 'PostController@logout')->name('logout');
Route::get('/dashboard', 'PostController@index')->name('dashboard');

Route::group(['middleware' => ['auth']], function () {
        //
        
    // Manage Akun//
    Route::name('manage-akun.')->prefix('manage-akun')->group(function() {
        Route::get('', 'AnggotaController@index')->name('index');
        Route::get('create', 'AnggotaController@create')->name('create');
        Route::post('store', 'AnggotaController@store')->name('store');
        Route::get('show/{users_id}', 'AnggotaController@show')->name('show');
        Route::get('edit/{users_id}', 'AnggotaController@edit')->name('edit');
        Route::put('update/{id}', 'AnggotaController@update')->name('update');
        Route::get('status/{id}','AnggotaController@status')->name('status');
    });

    // Role Anggota//
    Route::name('roles.')->prefix('roles')->group(function() {
        Route::get('', 'RolesController@index')->name('index');
        Route::get('add', 'RolesController@add')->name('add');
        Route::post('store', 'RolesController@store')->name('store');
        Route::get('edit/{id}', 'RolesController@edit')->name('edit');
        Route::put('update/{id}', 'RolesController@update')->name('update');
        Route::delete('destroy/{id}', 'RolesController@destroy')->name('destroy');
    });


    // Manage Buku //
    Route::name('master-buku.')->prefix('master-buku')->group(function() {
        Route::get('', 'BukuController@index')->name('index');
        Route::get('blank', 'BukuController@blank')->name('blank');
        Route::get('nonaktif', 'BukuController@nonaktif')->name('nonaktif');
        Route::get('create', 'BukuController@create')->name('create');
        Route::post('load', 'BukuController@load')->name('load');
        Route::get('show/{buku_id}', 'BukuController@show')->name('show');
        Route::get('edit/{buku_id}', 'BukuController@edit')->name('edit');
        Route::put('update/{buku_id}', 'BukuController@update')->name('update');
        Route::delete('destroy/{buku_id}', 'BukuController@destroy')->name('destroy');
        Route::get('status/{id}','BukuController@status')->name('status');
        Route::get('ambil/{id}','BukuController@ambil')->name('ambil');
    });

    // Peminjaman Buku //
    Route::name('pinjam-buku.')->prefix('pinjam-buku')->group(function() {
        Route::get('', 'PeminjamanController@index')->name('index');
        Route::get('cek/{id}', 'PeminjamanController@cek')->name('cek');
        Route::get('form', 'PeminjamanController@form')->name('form');
        Route::post('save', 'PeminjamanController@save')->name('save');
        Route::get('setujui/{id}', 'PeminjamanController@setujui')->name('setujui');
        Route::get('tolak/{id}', 'PeminjamanController@tolak')->name('tolak');
    });

    // Pengembalian Buku //
    Route::name('pengembalian-buku.')->prefix('pengembalian-buku')->group(function() {
        Route::get('', 'PengembalianController@index')->name('index');
        Route::get('/{id}', 'PengembalianController@kembalikan')->name('kembalikan');
        Route::get('edit/{pinjam_id}', 'PengembalianController@edit')->name('edit');
        Route::put('update', 'PengembalianController@update')->name('update');
    });

    // Laporan Peminjaman Buku //
    Route::name('laporan.')->prefix('laporan')->group(function() {
        Route::get('', 'LaporanController@index')->name('index');
    });

});

perpustakaan/app/Http/Controllers/AnggotaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;


class AnggotaController extends Controller
{
    //
    
    public function index()
    {
        $userdata = DB::table('users')
        ->join('roles as r', 'r.id','=','users.roles_id')
        ->select('users.*', 'r.peran')
        ->get(['users.*', 'r.id as roles_id']);

        return view('anggota.index',compact('userdata'));
    }

    public function create()
    {
        $ambilroles = DB::table('roles')->get();
        return view('anggota.create', compact('ambilroles'));
    }

    public function store(Request $request)
    {
        $request->validate(
            [
            'name' => 'required',
            'email' => 'required',
            'password' => 'required',
            'status_akun' => 'required',
            'profil' => 'required|mimes:png,jpg,jpeg',
            'nik' => 'required', 
            'roles_id' => '',
            ],
            [
                'name.required' => 'name harus diisi',
                'email.required'  => 'email harus diisi',
                'password.required'  => 'password harus diisi',
                'status_akun.required'  => 'peran harus diisi',
                'profil.required' => 'profil harus diisi',
                'nik.required'  => 'nik harus diisi', 
            ],
            
        );

        $fileName = time().'.'.$request->profil->extension();

        DB::table('users')->insert(
            [
                'name' => $request['name'], 
                'email' => $request['email'],
                'password' => bcrypt($request['password']),
                'status_akun' => $request['status_akun'],
                'profil' => $fileName,
                'nik' => $request['nik'],
                'roles_id' => $request['roles_id'],

            ]
        );

        $request->profil->move(public_path('image'), $fileName);
  
        return redirect()->route('manage-akun.index')->with('best', 'Data  Anggota berhasil ditambahkan!');;
    }

    public function show($id)
    {
        $userdata = DB::table('users')->where('id', $id)->get();
        $id = $userdata->id;

        return view('anggota.show', compact('userdata', 'id'));
    }

    public function edit($id)
    {
        $userdata = DB::table('users')->where('id', $id)->get();

        return view('anggota.edit', compact('userdata'));
    }

    public function update(Request $request, $id)
    {
        $request->validate(
            [
            'name' => 'required',
            'status_akun' => 'required',
            'nik' => 'required', 
            'roles_id' => 'required',
            ],
            [
                'name.required' => 'name harus diisi',
                'status_akun.required'  => 'status harus diisi',
                'nik.required'  => 'nik harus diisi', 
                'roles_id.required' => 'roles harus diisi',
            ]
        );

        DB::table('users')
        ->where('id',$id)
        ->update(
            [
                'name' => $request['name'], 
                'status_akun' => $request['status_akun'],
                'nik' => $request['nik'],
                'roles_id' => $request['roles_id'],
              ]
            );
        return redirect()->route('manage-akun.index')->with('success', 'Data Berhasil Disimpan');;
    }

    public function status($id)
    {
        $userdata = DB::table('users')->where('id',$id)->first(); 
        $datacek = $userdata->status_akun;
        if ($datacek == 1){
            DB::table('users')->where('id',$id)->update([
                'status_akun'=>0
            ]);
        } else {
            DB::table('users')->where('id',$id)->update([
                'status_akun'=>1
            ]);
        }
        return redirect()->route('manage-akun.index')->with('success', 'Status Anggota Berhasil diubah');
    }


}

perpustakaan/resources/views/anggota/create.blade.php
@extends('layout.dasbor')
 
@section('judul')
Tambah Anggota
@endsection

@section('konten')
<form action="{{ route('manage-akun.store') }}" method="post" enctype="multipart/form-data">
    @csrf 
    <div class="form-group">
      <input type="text" name="name" class="form-control form-control-user" id="exampleFirstName"
          placeholder="Full Name">
    </div>
    @error('name')
       <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div class="form-group">
      <input type="email" name="email" class="form-control form-control-user" id="exampleInputEmail"
          placeholder="Email Address">
    </div>
    @error('email')
       <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div class="form-group row">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <input type="password" class="form-control form-control-user" name="password"
            id="exampleInputPassword" placeholder="Password ">
       </div>
       @error('password')
          <div class="alert alert-danger">{{ $message }}</div>
       @enderror
       <div class="col-sm-6">
          <input type="password" class="form-control form-control-user" name="password_confirmation"
              id="exampleRepeatPassword" placeholder="Repeat Password">
       </div>
        @error('password_confirmation')
           <div class="alert alert-danger">{{ $message }}</div>
        @enderror
    </div>
    <div class="form-group">
      <input type="number" name="status_akun"  class="form-control form-control-user" id="exampleroles"
          placeholder="status_akun">
    </div>
    @error('status_akun')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div class="form-group mb-4">
      <input type="file" name="profil"  class="form-control form-control-user" id="exampleprofil"
          placeholder="profil">
    </div>
    @error('profil')
       <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <div class="form-group">
      <input type="number" name="nik"  class="form-control form-control-user" id="exampleNIK"
          placeholder="NIK">
    </div>
    <div class="form-group">
      <select class="form-control" name="roles_id" id="exampleRepeatPassword"  required="">
          <option value=> Role </option>
          <option value="1">1</option>
          <option value="2">2</option>
      </select>
    </div>
    @error('roles_id')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
    <button type="submit" class="btn btn-primary">Register Account</button>
    <hr>
</form>

@endsection

perpustakaan/resources/views/anggota/edit.blade.php
@extends('layout.dasbor')
@section('judul')
Edit Anggota 
@endsection

@section('konten')
  @foreach ($userdata as $item)
  <form action="{{ route('manage-akun.update',$item->id) }}" method="POST">
      @csrf
      @method('put')
      <div class="form-group">
        <label >Nama Anggota</label>
        <input type="text" value="{{ $item->name }}" name="name" class="form-control">
      </div>
      @error('name')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <div class="form-group">
        <label >Status</label>
        <input type="number" value="{{ $item->status_akun }}" name="status_akun" class="form-control">
      </div>
      @error('status_akun')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <div class="form-group">
        <label >nik</label>
        <input type="number" value="{{ $item->nik }}" name="nik" class="form-control">
      </div>
      @error('nik')
        <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <div class="form-group">
        <select class="form-control" value="{{ $item->roles_id }}" name="roles_id" id="exampleRepeatPassword"  required="">
            <option value=> Role </option>
            <option value="1">1</option>
            <option value="2">2</option>
        </select>
    </div>
      <button type="submit" class="btn btn-primary">Update</button>
      @error('roles_id')
       <div class="alert alert-danger">{{ $message }}</div>
      @enderror
  </form>
  @endforeach
@endsection

perpustakaan/resources/views/anggota/index.blade.php
@extends('layout.dasbor')
 
@section('konten')

<a href="{{ route('manage-akun.create') }}" class="btn btn-primary btn-sm mb-3"><i class="fas fa-plus"></i>         Tambah Anggota</a>
<button type="submit" value="Refresh" class="btn btn-secondary btn-sm mb-3"><i class="fas fa-sync" onClick="document.location.reload(true)">             Refresh</i></button>
@if (session('success'))
    <div class="alert alert-success">
      {{ session('success') }}
    </div>
@endif

<div class="card-body table-responsive p-0" style="height: 300px;">
<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Keadaan</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Status</th>
      <th scope="col">Profil</th>
      <th scope="col">NIK</th>
      <th scope="col">Roles_id</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
      @forelse ($userdata as $key => $item)
          <tr>
              <td>{{$key + 1}}</td>
              <td>
                @if($item->status_akun == 1)
                <a href="{{ route('manage-akun.status',$item->id) }}" class="btn btn-danger btn-sm">Batalkan Disetujui</a>
                @else
                <a href="{{ route('manage-akun.status',$item->id) }}" class="btn btn-success btn-sm">Setujui</a>
                @endif 
              </td>
              <td>{{$item->name}}</td>
              <td>{{$item->email}}</td>
              <td><span class="badge {{ ($item->status_akun == 1) ? 'bg-success' : 'bg-danger' }}">{{ ($item->status_akun == 1) ? 'Telah Disetujui' : 'Belum Disetujui' }}</span></td>
              <td>
                <img src="{{asset('image/'.$item->profil)}}" style="width: 50px" alt="">
              </td>
              <td>{{$item->nik}}</td>
              <td>{{$item->peran}}</td>
              <td>

                  <form action="/manage/anggota/{{$item->id}}" method="POST">
                        @csrf
                        <a href="{{ route('manage-akun.show',$item->id) }}" class="btn btn-info btn-sm"><i class="fas fa-eye"></i></a>
                        <a href="{{ route('manage-akun.edit',$item->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-pen"></i></a>
                  </form>
              </td>
          </tr>
      @empty
         <tr>
             <td>Data Masih Kosong</td>
         </tr>
      @endforelse
  </tbody>
</table>
</div>
@endsection

@section('scripts')
  <script type="text/javascript">
      $(document).ready(function(){
          // btn refresh 
            $('.btn-refresh').click(function(e){
                e.preventDefault();
                $('.preloader').fadeIn();
                location.reload();
            })
       })
  </script>
@endsection 

perpustakaan/resources/views/anggota/show.blade.php
@extends('layout.dasbor')
 
@section('judul')
 Detail Anggota {{$userdata->name}}
 @endsection

 @section('konten')
 <h1>{{$userdata->name}}</h1>
 <p>{{$userdata->status_akun}}</p>
 <p>{{$userdata->profil}}</p>
 <p>{{$userdata->nik}}</p>
 <p>{{$userdata->roles_id}}</p>


<a href="{{ route('manage-akun.index') }}" class="btn btn-secondary">Back</a>

 @endsection