perpustakaan/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('/');
Route::get('/about', 'AboutController@about')->name('about');
Route::get('/katalog', 'KatalogController@koleksi')->name('katalog');
Route::get('/lokasi', 'KatalogController@lokasi')->name('lokasi');
Route::get('/informasi', 'KatalogController@informasi')->name('informasi');


// register dan login//
Route::get('/register', 'PostController@register')->name('register');
Route::post('/data/register', 'PostController@store');
Route::get('/login', 'PostController@login')->name('login');
Route::post('/simpan', 'PostController@simpan')->name('simpan');
Route::get('/logout', 'PostController@logout')->name('logout');
Route::get('/dashboard', 'PostController@index')->name('dashboard');

Route::group(['middleware' => ['auth']], function () {
        //
        
    // Manage Akun//
    Route::name('manage-akun.')->prefix('manage-akun')->group(function() {
        Route::get('', 'AnggotaController@index')->name('index');
        Route::get('create', 'AnggotaController@create')->name('create');
        Route::post('store', 'AnggotaController@store')->name('store');
        Route::get('show/{users_id}', 'AnggotaController@show')->name('show');
        Route::get('edit/{users_id}', 'AnggotaController@edit')->name('edit');
        Route::put('update/{id}', 'AnggotaController@update')->name('update');
        Route::get('status/{id}','AnggotaController@status')->name('status');
    });

    // Role Anggota//
    Route::name('roles.')->prefix('roles')->group(function() {
        Route::get('', 'RolesController@index')->name('index');
        Route::get('add', 'RolesController@add')->name('add');
        Route::post('store', 'RolesController@store')->name('store');
        Route::get('edit/{id}', 'RolesController@edit')->name('edit');
        Route::put('update/{id}', 'RolesController@update')->name('update');
        Route::delete('destroy/{id}', 'RolesController@destroy')->name('destroy');
    });


    // Manage Buku //
    Route::name('master-buku.')->prefix('master-buku')->group(function() {
        Route::get('', 'BukuController@index')->name('index');
        Route::get('blank', 'BukuController@blank')->name('blank');
        Route::get('nonaktif', 'BukuController@nonaktif')->name('nonaktif');
        Route::get('create', 'BukuController@create')->name('create');
        Route::post('load', 'BukuController@load')->name('load');
        Route::get('show/{buku_id}', 'BukuController@show')->name('show');
        Route::get('edit/{buku_id}', 'BukuController@edit')->name('edit');
        Route::put('update/{buku_id}', 'BukuController@update')->name('update');
        Route::delete('destroy/{buku_id}', 'BukuController@destroy')->name('destroy');
        Route::get('status/{id}','BukuController@status')->name('status');
        Route::get('ambil/{id}','BukuController@ambil')->name('ambil');
    });

    // Peminjaman Buku //
    Route::name('pinjam-buku.')->prefix('pinjam-buku')->group(function() {
        Route::get('', 'PeminjamanController@index')->name('index');
        Route::get('cek/{id}', 'PeminjamanController@cek')->name('cek');
        Route::get('form', 'PeminjamanController@form')->name('form');
        Route::post('save', 'PeminjamanController@save')->name('save');
        Route::get('setujui/{id}', 'PeminjamanController@setujui')->name('setujui');
        Route::get('tolak/{id}', 'PeminjamanController@tolak')->name('tolak');
    });

    // Pengembalian Buku //
    Route::name('pengembalian-buku.')->prefix('pengembalian-buku')->group(function() {
        Route::get('', 'PengembalianController@index')->name('index');
        Route::get('/{id}', 'PengembalianController@kembalikan')->name('kembalikan');
        Route::get('edit/{pinjam_id}', 'PengembalianController@edit')->name('edit');
        Route::put('update', 'PengembalianController@update')->name('update');
    });

    // Laporan Peminjaman Buku //
    Route::name('laporan.')->prefix('laporan')->group(function() {
        Route::get('', 'LaporanController@index')->name('index');
    });

});

perpustakaan/app/Http/Controllers/PengembalianController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PengembalianController extends Controller
{
    
    public function index()
    {
        if (Auth::user()->roles_id ==1) {
            $pinjamdata = DB::table('pinjam')
            ->join('buku as b', 'b.id', '=','pinjam.buku_id')
            ->select('pinjam.*', 'b.judul')
            ->whereIn('status',[1,3])
            ->get(['pinjam.*', 'b.id as buku_id']);
        } else {
            $pinjamdata = DB::table('pinjam')
            ->join('buku as b', 'b.id', '=','pinjam.buku_id')
            ->select('pinjam.*', 'b.judul')
            ->where('user_id', Auth::user()->name)
            ->whereIn('status',[1,3])
            ->get(['pinjam.*', 'b.id as buku_id']);
        }

        return view('pengembalian.index',compact('pinjamdata'));
    }

    public function kembalikan($id)
    {
        $pinjamdata = DB::table('pinjam')->where('id', $id)->update(['status'=>3]);
        return redirect()->route('pengembalian-buku.index');
    }

    public function edit($id)
    {
        $pinjamdata = DB::table('pinjam')
        ->join('buku as b', 'b.id', '=','pinjam.buku_id')
        ->select('pinjam.*', 'b.judul')
        ->whereIn('status',[1,3])
        ->get(['pinjam.*', 'b.id as buku_id']);

        return view('pengembalian.edit',compact('pinjamdata'));

    }

    public function update(Request $request)
    {
        $request->validate(
            [
            'tanggal_pengembalian' => 'required',
            ],
            [
                'tanggal_pengembalian.required' => 'tanggal harus diisi',
            ]
        );

        DB::table('pinjam')
              ->update(
                  [
                    'tanggal_pengembalian' => date('Y-m-d H:i:s'), 
                  ]
                );

        return redirect('/pengembalian-buku')->with('best', 'Data Berhasil Disimpan');
    }

  
}

perpustakaan/resources/views/pengembalian/edit.blade.php
@extends('layout.dasbor')
@section('judul')

@endsection

@section('konten')
  <form action="{{ route('pengembalian-buku.update') }}" method="POST">
      @csrf
      @method('put')
      <div class="form-group">
        <label >Tanggal Pengembalian</label>
        <input type="date" name="tanggal_pengembalian" class="form-control">
      </div>
      @error('tanggal_pengembalian')
         <div class="alert alert-danger">{{ $message }}</div>
      @enderror
      <button type="submit" class="btn btn-primary">Update</button>
      @error('tanggal_pengembalian')
       <div class="alert alert-danger">{{ $message }}</div>
      @enderror
  </form>
@endsection

perpustakaan/resources/views/pengembalian/index.blade.php
@extends('layout.dasbor')
 
@section('konten')

<button type="submit" value="Refresh" class="btn btn-secondary btn-sm mb-3"><i class="fas fa-sync" onClick="document.location.reload(true)">             Refresh</i></button>
@if (session('best'))
    <div class="alert alert-success">
      {{ session('best') }}
    </div>
@endif

<div class="card-body table-responsive p-0" style="height: 300px;">
   <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">User</th>
                <th scope="col">Buku</th>
                <th scope="col">Jenis Transaksi</th>
                <th scope="col">Tanggal Pengajuan</th>
                <th scope="col">Status</th>
                <th scope="col">Tanggal Pengembalian</th>
                @if(Auth::user()->roles_id == 1)
                <th scope="col">Action</th>
                @endif
            </tr>
        </thead>
        <tbody>
          @forelse ($pinjamdata as $key => $item)
              <tr>
                  @if( Auth::user()->id)
                  <td>{{$key + 1}}</td>
                  <td>{{$item->user_id}}</td>
                  <td>{{$item->judul}}</td>
                  <td>{{$item->jenis_transaksi}}</td>
                  <td>{{$item->tanggal_pengajuan}}</td>
                  @if ($item->status == 1)
                  <td><span class="bg-success">Sedang Di Pinjam</span></td>
                  @else 
                  <td><span class="bg-primary">Sudah Di Kembalikan</span></td>
                  @endif
                  @if ($item->status ==3)
                  <td>{{$item->tanggal_pengembalian}}</td>
                  @else
                  <td></td>
                  @endif
                  @if(Auth::user()->roles_id == 1)
                  @if ($item->status ==1)
                  <td>
                    <a href="{{ route('pengembalian-buku.kembalikan',$item->id) }}" class="btn btn-primary btn-sm">Kembalikan</a>
                  </td>
                  @else
                  <td>
                    <form action="" method="POST">
                        @csrf
                        <a href="{{ route('pengembalian-buku.edit',$item->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-pen"></i></a>
                  </form>
                  </td>
                  @endif
                  @endif
                  @endif
              </tr>
          @empty
               <tr>
                  <td>Data Masih Kosong</td>
              </tr>
          @endforelse
      </tbody>
 </table>
</div>
@endsection